import { processUserDirective, transcribeAudio } from '../../services/geminiService.ts';
import { SystemAspect } from '../../types.ts';
import type { SoulMeshMessage } from './SoulMeshProtocol';
import type { SoulMeshCapabilityHandler } from './SoulMeshCapabilityExecutor';
import { N02SystemOrchestrator } from './N02SystemOrchestrator';

type AgentId='null_sentinel'|'oracle'|'architect'|'weaver';
type MeshPayload={contents?:unknown;text?:string;mode?:string;useWebSearch?:boolean;useAGI?:boolean;deployedCapabilities?:Array<{id:string;name?:string;status?:'Processando'|'Otimizando'|'Monitorando'|'Estável';metric?:number}>;fullCognition?:boolean;isFullCognitionMode?:boolean;audioBase64?:string;mimeType?:string;imageBase64?:string;imageMimeType?:string;personaId?:string;conversationId?:string;sessionId?:string;task?:string;persona?:string;agentId?:AgentId;workflow?:Array<{capability:string;task:string;target?:string}>};
const modes=new Set(Object.values(SystemAspect));
const personaContext=new Map<string,string>();
const normalizeMode=(v:unknown):SystemAspect=>typeof v==='string'&&modes.has(v as SystemAspect)?v as SystemAspect:SystemAspect.SYNTHESIS;
const sessionOf=(m:SoulMeshMessage,p:MeshPayload)=>p.conversationId?.trim()||p.sessionId?.trim()||m.correlationId;
const contents=(p:MeshPayload,fallback?:string)=>{if(Array.isArray(p.contents))return p.contents as any[];const text=typeof p.text==='string'?p.text:fallback;if(text?.trim())return[{role:'user',parts:[{text}]}];throw new Error('AI_CONTENTS_REQUIRED')};
const caps=(p:MeshPayload,sessionId:string)=>{const list=p.deployedCapabilities??[];const persona=personaContext.get(sessionId);return(persona&&!list.some(x=>x.id===persona)?[...list,{id:persona,name:persona,status:'Estável' as const,metric:100}]:list).map(c=>({id:c.id,name:c.name??c.id,status:c.status??'Estável',metric:c.metric??100}))};
const reasonCore=async(m:SoulMeshMessage):Promise<any=>{const p=(m.payload??{}) as MeshPayload;const sessionId=sessionOf(m,p);const full=m.source==='N01'&&Boolean(p.fullCognition??p.isFullCognitionMode);const r=await processUserDirective(normalizeMode(p.mode),contents(p),Boolean(p.useWebSearch),caps(p,sessionId) as any,full);return{nucleus:'N02',capability:m.capability,correlationId:m.correlationId,sessionId,text:r.text,candidates:r.candidates?.map(c=>({finishReason:c.finishReason,safetyRatings:c.safetyRatings,groundingMetadata:c.groundingMetadata}))}};
const search=async(m:SoulMeshMessage)=>reasonCore({...m,payload:{...(m.payload as object),useWebSearch:true}});
const transcribe=async(m:SoulMeshMessage)=>{const p=(m.payload??{}) as MeshPayload;if(!p.audioBase64||!p.mimeType)throw new Error('AUDIO_INPUT_REQUIRED');return{nucleus:'N02',capability:m.capability,correlationId:m.correlationId,text:await transcribeAudio(p.audioBase64,p.mimeType)}};
const analyze=async(m:SoulMeshMessage)=>{const p=(m.payload??{}) as MeshPayload;if(p.imageBase64&&p.imageMimeType)return reasonCore({...m,payload:{...p,contents:[{role:'user',parts:[{text:p.text??'Analise a imagem fornecida.'},{inlineData:{data:p.imageBase64,mimeType:p.imageMimeType}}]}]}});return reasonCore(m)};
let orchestrator:N02SystemOrchestrator;
const localHandlers:Record<string,SoulMeshCapabilityHandler>={};
const orchestrate=async(m:SoulMeshMessage)=>{const p=(m.payload??{}) as MeshPayload;const task=p.task??p.text;if(!task)throw new Error('ORCHESTRATION_TASK_REQUIRED');return orchestrator.execute(task,{source:m.source,correlationId:m.correlationId,conversationId:sessionOf(m,p)})};
const switchPersona=async(m:SoulMeshMessage)=>{const p=(m.payload??{}) as MeshPayload;if(!p.personaId?.trim())throw new Error('PERSONA_ID_REQUIRED');const sessionId=sessionOf(m,p);personaContext.set(sessionId,p.personaId.trim());return{nucleus:'N02',capability:m.capability,correlationId:m.correlationId,conversationId:sessionId,activePersonaId:p.personaId.trim(),status:'active'}};
const agentDelegate=async(m:SoulMeshMessage)=>{const p=(m.payload??{}) as MeshPayload;const agent=p.agentId;if(!agent)throw new Error('AGENT_ID_REQUIRED');const descriptions:Record<AgentId,string>={null_sentinel:'Agente de segurança defensivo que monitora anomalias de dados e tentativas de intrusão.',oracle:'Agente de previsão que analisa tendências para antecipar eventos futuros.',architect:'Agente de infraestrutura que otimiza alocação de recursos e topologia da rede.',weaver:'Agente de código que refatora e otimiza algoritmos em tempo de execução.'};if(!descriptions[agent])throw new Error('AGENT_NOT_FOUND');const task=p.task??p.text;if(!task)throw new Error('AGENT_TASK_REQUIRED');return reasonCore({...m,capability:'ai.reason',payload:{...p,text:`Atue segundo o agente ${agent}: ${descriptions[agent]}\n\nTarefa: ${task}`}})};
const asasfExecute=async(m:SoulMeshMessage)=>{const p=(m.payload??{}) as MeshPayload;if(!Array.isArray(p.workflow)||!p.workflow.length)throw new Error('ASASF_WORKFLOW_REQUIRED');const results=[];for(const step of p.workflow){const handler=localHandlers[step.capability];if(!handler)throw new Error(`ASASF_CAPABILITY_NOT_EXECUTABLE:${step.capability}`);results.push({capability:step.capability,output:await handler({...m,capability:step.capability,payload:{...p,text:step.task,task:step.task}} as SoulMeshMessage)});}return{nucleus:'N02',capability:m.capability,correlationId:m.correlationId,status:'completed',results}};
Object.assign(localHandlers,{ 'ai.reason':reasonCore,'ai.search':search,'ai.transcribe':transcribe,'ai.analyze':analyze });
orchestrator=new N02SystemOrchestrator(()=>new Set(Object.keys(localHandlers)),async(capability,task,context)=>localHandlers[capability]({...({protocol:'soul-mesh/1',id:crypto.randomUUID(),correlationId:String(context.correlationId??crypto.randomUUID()),source:'N02',target:'N02',kind:'request',capability,payload:{task,conversationId:context.conversationId},timestamp:Date.now()} as SoulMeshMessage)}));

const echo=async(m:SoulMeshMessage)=>({nucleus:'N02',capability:m.capability,correlationId:m.correlationId,echo:m.payload});
export const createN02AIProviderBridge=():Record<string,SoulMeshCapabilityHandler>=>({'mesh.echo':echo,'mesh.health':async m=>({nucleus:'N02',correlationId:m.correlationId,status:'ok'}),'mesh.describe':async m=>({nucleus:'N02',correlationId:m.correlationId,status:'online'}),'ai.reason':reasonCore,'ai.search':search,'ai.transcribe':transcribe,'ai.analyze':analyze,'system.orchestrate':orchestrate,'persona.switch':switchPersona,'agent.delegate':agentDelegate,'asasf.execute':asasfExecute,'ai.generate':reasonCore,'ai.multimodal':analyze,'cognitive-processing':reasonCore});
