export type N02ExternalProvider = {
  id: string;
  source: string;
  revision: string;
  canonicalOwner: string;
  meshTargets: readonly string[];
  capabilities: readonly string[];
  n02Functions: readonly string[];
  directAffinity: boolean;
  state: 'CATALOG_BOUND' | 'ADAPTER_BOUND';
};

const DATA = [
  [
    "superpowers",
    "https://github.com/obra/superpowers",
    "8ca22dba9a94f28898bbce59f2537ff4d87c747d",
    "N07",
    [
      "N07"
    ],
    [
      "agentic-skills",
      "subagents",
      "planning",
      "tdd",
      "review",
      "debugging"
    ],
    [
      "skill_acquisition",
      "strategic_planning"
    ]
  ],
  [
    "superagi",
    "https://github.com/TransformerOptimus/SuperAGI",
    "c3c1982e7bd6a11cfed53c5a193ea502f924b1b6",
    "N07",
    [
      "N07"
    ],
    [
      "autonomous-agents",
      "tools",
      "memory",
      "multimodal",
      "telemetry"
    ],
    [
      "emergent_cognition",
      "uci"
    ]
  ],
  [
    "langgraph",
    "https://github.com/langchain-ai/langgraph",
    "157a06dda988d85afeb8751ff27b35ab3f4f8bf4",
    "N07",
    [
      "N07",
      "N01"
    ],
    [
      "stateful-agents",
      "durable-workflows",
      "orchestration"
    ],
    [
      "strategic_planning",
      "cot_drc"
    ]
  ],
  [
    "crewai",
    "https://github.com/crewAIInc/crewAI",
    "8078f9130c35a47be95d4a55bf1d73b3fd44fc88",
    "N07",
    [
      "N07"
    ],
    [
      "multi-agent-crews",
      "flows",
      "role-specialization"
    ],
    [
      "emergent_cognition",
      "strategic_planning"
    ]
  ],
  [
    "microsoft-agent-framework",
    "https://github.com/microsoft/agent-framework",
    "a2f4506c0ba30cea7c9bbe907fc158c0db2cc6a3",
    "N07",
    [
      "N07"
    ],
    [
      "agents",
      "workflows",
      "MCP",
      "A2A"
    ],
    [
      "uci",
      "emergent_cognition"
    ]
  ],
  [
    "openhands",
    "https://github.com/OpenHands/OpenHands",
    "2414d6ee5e31bede2e78211f72b58e9949575a75",
    "N06",
    [
      "N06"
    ],
    [
      "software-agents",
      "tool-use",
      "execution"
    ],
    [
      "scre",
      "einstein_code"
    ]
  ],
  [
    "metagpt",
    "https://github.com/FoundationAgents/MetaGPT",
    "11cdf466d042aece04fc6cfd13b28e1a70341b1f",
    "N06",
    [
      "N06"
    ],
    [
      "role-based-agents",
      "multi-agent-collaboration",
      "software-process"
    ],
    [
      "ecas",
      "strategic_planning"
    ]
  ],
  [
    "agentscope",
    "https://github.com/agentscope-ai/agentscope",
    "72f3f6fa0b2fc38b8517f408ab616f0f2bd229e6",
    "N03",
    [
      "N03",
      "N07"
    ],
    [
      "agents",
      "teams",
      "tools",
      "memory",
      "sandbox",
      "A2A",
      "voice"
    ],
    [
      "multimodal_cortex",
      "emergent_cognition"
    ]
  ],
  [
    "letta-code",
    "https://github.com/letta-ai/letta-code",
    "1fcc9666817ab852bc2532a3a989f712e1fd6c19",
    "N01",
    [
      "N01"
    ],
    [
      "stateful-agents",
      "persistent-memory",
      "identity"
    ],
    [
      "skill_acquisition",
      "conversation.memory"
    ]
  ],
  [
    "browser-use",
    "https://github.com/browser-use/browser-use",
    "302d8fcb245a7a63fb7531a4734c9ce3c7792779",
    "N04",
    [
      "N04"
    ],
    [
      "browser-agents",
      "web-automation"
    ],
    [
      "uci"
    ]
  ],
  [
    "smolagents",
    "https://github.com/huggingface/smolagents",
    "c30b115286e000e98711fae5e85993547b73d826",
    "N06",
    [
      "N06"
    ],
    [
      "code-agents",
      "tools",
      "MCP",
      "multimodal"
    ],
    [
      "skill_acquisition",
      "emergent_cognition"
    ]
  ],
  [
    "pydantic-ai",
    "https://github.com/pydantic/pydantic-ai",
    "6bc07cf18b0641ea92343d8c589cfb922108b802",
    "N01",
    [
      "N01",
      "JEV"
    ],
    [
      "typed-agents",
      "tools",
      "subagents",
      "durable-execution"
    ],
    [
      "uci",
      "ethical_governance"
    ]
  ],
  [
    "llama-index",
    "https://github.com/run-llama/llama_index",
    "962940ddc079cc21701d28d1237c84c82a7c5164",
    "N05",
    [
      "N05"
    ],
    [
      "RAG",
      "indexing",
      "retrieval",
      "agent-workflows"
    ],
    [
      "eus",
      "conversation.memory"
    ]
  ],
  [
    "dspy",
    "https://github.com/stanfordnlp/dspy",
    "ba3f9198efe5d125c7c1a2b40b1f1e6166209bd2",
    "N06",
    [
      "N06"
    ],
    [
      "LM-programming",
      "optimization",
      "reasoning-pipelines"
    ],
    [
      "einstein_reasoning",
      "mlfg"
    ]
  ],
  [
    "whisper",
    "https://github.com/openai/whisper",
    "86098128c0b4f24f0e2aa2994de830614b474227",
    "N03",
    [
      "N03"
    ],
    [
      "speech-to-text"
    ],
    [
      "acai",
      "multimodal_cortex"
    ]
  ],
  [
    "kokoro",
    "https://github.com/hexgrad/kokoro",
    "dfb907a02bba8152ca444717ca5d78747ccb4bec",
    "N03",
    [
      "N03"
    ],
    [
      "text-to-speech"
    ],
    [
      "multimodal_cortex"
    ]
  ],
  [
    "everything-claude-code",
    "https://github.com/affaan-m/ECC",
    "ef648e01899ba3e8dc6371642deaaf64b4477775",
    "N07",
    [
      "N07"
    ],
    [
      "skills",
      "instincts",
      "memory-optimization",
      "continuous-learning",
      "security-scanning",
      "research-first-development"
    ],
    [
      "skill_acquisition",
      "scre"
    ]
  ],
  [
    "swarmclaw",
    "https://github.com/swarmclawai/swarmclaw",
    "ed38ba5329c20e48c03b4a4028f4a76a1a75e2d1",
    "N07",
    [
      "N07"
    ],
    [
      "multi-agent-swarms",
      "memory",
      "MCP",
      "delegation",
      "scheduling"
    ],
    [
      "emergent_cognition",
      "cot_drc"
    ]
  ],
  [
    "mem0",
    "https://github.com/mem0ai/mem0",
    "abb81c88e1f738a8117d8293530fbc31a5ef8fd9",
    "N06",
    [
      "N06",
      "SARA"
    ],
    [
      "persistent-agent-memory",
      "memory-management"
    ],
    [
      "conversation.memory",
      "eus"
    ]
  ],
  [
    "letta",
    "https://github.com/letta-ai/letta",
    "5bcdd177d70fa2b31a754cfcd801e77b2e1ab16a",
    "N06",
    [
      "N06",
      "SARA"
    ],
    [
      "stateful-agents",
      "advanced-memory",
      "learning"
    ],
    [
      "conversation.memory",
      "emergent_cognition"
    ]
  ],
  [
    "langfuse",
    "https://github.com/langfuse/langfuse",
    "f75c661dbe8c6b85523c81486b39e8403ac2c141",
    "N07",
    [
      "N07",
      "SARA"
    ],
    [
      "tracing",
      "evaluation",
      "datasets",
      "LLM-observability"
    ],
    [
      "clareira.metrics",
      "ethical_governance"
    ]
  ],
  [
    "vllm",
    "https://github.com/vllm-project/vllm",
    "7dfe3338d5f15dd3ccb233326aa65fde46e427ad",
    "N07",
    [
      "N07"
    ],
    [
      "high-throughput-inference",
      "serving"
    ],
    [
      "ai.generate",
      "inference.reason"
    ]
  ],
  [
    "sglang",
    "https://github.com/sgl-project/sglang",
    "65f759144d192671af5301568113e38686999871",
    "N07",
    [
      "N07"
    ],
    [
      "high-performance-serving",
      "multimodal-serving"
    ],
    [
      "ai.generate",
      "inference.reason"
    ]
  ],
  [
    "ray",
    "https://github.com/ray-project/ray",
    "f8a314bf077c9772fee2a8a1073368ca2ef9360b",
    "N07",
    [
      "N07"
    ],
    [
      "distributed-compute",
      "actors",
      "parallelism",
      "AI workloads"
    ],
    [
      "resource.dcrs",
      "cot_arhd"
    ]
  ],
  [
    "megatron-lm",
    "https://github.com/NVIDIA/Megatron-LM",
    "160561d12927b36b1429ac35f86793cb2ece0ec6",
    "N07",
    [
      "N07"
    ],
    [
      "large-scale-transformer-training",
      "distributed-training"
    ],
    [
      "neural_forge",
      "resource.dcrs"
    ]
  ]
] as const;

export const N02_EXTERNAL_PROVIDERS: readonly N02ExternalProvider[] = DATA.map(
  ([id, source, revision, canonicalOwner, meshTargets, capabilities, n02Functions]) => ({
    id, source, revision, canonicalOwner, meshTargets, capabilities, n02Functions,
    directAffinity: ['superpowers','langgraph','crewai','microsoft-agent-framework','openhands','metagpt','agentscope','browser-use','smolagents','vllm','sglang','dspy'].includes(id),
    state: (id === 'vllm' || id === 'sglang') && (String(process.env.N02_VLLM_URL ?? '').trim() || String(process.env.N02_SGLANG_URL ?? '').trim())
      ? 'ADAPTER_BOUND'
      : 'CATALOG_BOUND',
  }),
) as readonly N02ExternalProvider[];

const INDEX = new Map(N02_EXTERNAL_PROVIDERS.map(provider => [provider.id, provider] as const));

export function resolveN02ExternalProvider(id: string): N02ExternalProvider {
  const provider = INDEX.get(id.trim().toLowerCase());
  if (!provider) throw new Error(`N02_EXTERNAL_PROVIDER_UNKNOWN:${id}`);
  return provider;
}

export function providersByFunction(functionId: string): readonly N02ExternalProvider[] {
  const needle = functionId.trim();
  return N02_EXTERNAL_PROVIDERS.filter(provider => provider.n02Functions.includes(needle));
}

export function describeN02ExternalCapabilityFabric() {
  return {
    nucleus: 'N02',
    providerCount: N02_EXTERNAL_PROVIDERS.length,
    directAffinityCount: N02_EXTERNAL_PROVIDERS.filter(provider => provider.directAffinity).length,
    providers: N02_EXTERNAL_PROVIDERS,
    rule: 'external source -> affinity -> native N02 handler or canonical owner; no external provider becomes a second authority',
  };
}
