import { discoverPeerCapabilities, requestPeerCapability, listRegisteredPeers, type NucleusId, type PeerDescription } from '../../api/soul-mesh/peer-client';
import { createSoulMeshMessage, type SoulMeshMessage } from './SoulMeshProtocol';
export type N02RemoteCapability={nucleus:NucleusId;id:string;executable:boolean};
export class SoulMeshRouter { constructor(readonly local:NucleusId='N02',readonly timeoutMs=15000){} async request<T=unknown>(target:NucleusId,capability:string,payload:T):Promise<SoulMeshMessage>{return requestPeerCapability(target,capability,payload,this.timeoutMs)} async sendEvent<T=unknown>(target:NucleusId,capability:string,payload:T):Promise<void>{await requestPeerCapability(target,capability,payload,this.timeoutMs)} async sendEventAndWait<T=unknown>(target:NucleusId,capability:string,payload:T):Promise<SoulMeshMessage>{return this.request(target,capability,payload)} ingest(message:SoulMeshMessage):SoulMeshMessage|undefined{return message.target===this.local?message:undefined} close():void{} }
export class N02PeerFabric { async describe(nucleus:NucleusId):Promise<PeerDescription>{return discoverPeerCapabilities(nucleus)} async discover(nucleus:NucleusId):Promise<N02RemoteCapability[]>{const d=await this.describe(nucleus);const executable=new Set(d.executableCapabilities??[]);return(d.declaredCapabilities??[]).map(id=>({nucleus,id,executable:executable.has(id)}))} async execute(nucleus:NucleusId,capability:string,payload:unknown){return requestPeerCapability(nucleus,capability,payload)} }
export const n02PeerFabric=new N02PeerFabric(); export const n02Router=new SoulMeshRouter();
export const N02_IN_CHANNELS=['N02_IN_N01','N02_IN_N03','N02_IN_N04','N02_IN_N05','N02_IN_N06'] as const; export const N02_OUT_CHANNELS=['N02_OUT_N01','N02_OUT_N03','N02_OUT_N04','N02_OUT_N05','N02_OUT_N06'] as const; export const N02_IN_ROUTES=['/mesh/in/N01','/mesh/in/N03','/mesh/in/N04','/mesh/in/N05','/mesh/in/N06'] as const;
export const createDiagnosticMessage=(target:NucleusId,capability:string,payload:unknown):SoulMeshMessage=>createSoulMeshMessage({source:'N02',target,kind:'request',capability,correlationId:crypto.randomUUID(),payload});
export async function runN02BrowserDiagnostic(){const peers=await listRegisteredPeers().catch(()=>[]);const out=await Promise.all((['N01','N03','N04','N05','N06'] as NucleusId[]).map(async target=>{try{const response=await n02Router.request(target,'mesh.echo',{diagnostic:true,channel:`N02_OUT_${target}`});return{target,out:'PASS',correlationId:response.correlationId}}catch(error){return{target,out:String(error).includes('TIMEOUT')?'TIMEOUT':'FAIL',error:String(error)}}}));const report={nucleus:'N02',timestamp:new Date().toISOString(),registeredPeers:peers.map((p:any)=>p.nucleus),channels:{in:N02_IN_ROUTES,out:N02_OUT_CHANNELS},out,ingress:'POST /mesh/in/Nxx with a valid peer token is the authenticated ingress test.'};console.info('[N02 MESH DIAGNOSTIC]',report);return report;}
