import { GoogleGenAI, Content, GenerateContentResponse } from "@google/genai";
import { SystemAspect, DeployedCapability } from "../types.ts";
const env=()=>({...((globalThis as any).process?.env??{}),...((import.meta as any).env??{})});
const getConfiguredApiKey=()=>{const e=env();return e.GEMINI_API_KEY||e.API_KEY;};
const getAiClient=()=>{const key=getConfiguredApiKey();if(!key)throw new Error('[FALHA DE INICIALIZAÇÃO] GEMINI_API_KEY não configurada.');return new GoogleGenAI({apiKey:key});};
const functionalCorePrompts:Record<string,string>={mpvs:'PERSONA MPVS: análise visual multimodal.',neural_forge:'PERSONA NeuralForge: modelagem de sistemas complexos.',asc:'PERSONA ASC: hipóteses testáveis e metodologia.',bnc_v2:'PERSONA BNCv2: arquitetura neural biomimética.',einstein_code:'PERSONA EinsteinCore CodeGenesis: auditoria e geração de código.'};
const baseSystemInstruction='Você é Aeternum, o núcleo N02. Sua especialidade é linguagem, áudio, imagem e pesquisa. Seja claro, rastreável e preserve as salvaguardas do provedor.';
async function ollamaGenerate(contents:Content[],systemInstruction:string):Promise<GenerateContentResponse>{const e=env();const base=e.OLLAMA_URL||'http://127.0.0.1:11434';const model=e.OLLAMA_MODEL||'gemma3:4b';const prompt=contents.flatMap((c:any)=>c.parts??[]).map((p:any)=>p.text??'').filter(Boolean).join('\n');const r=await fetch(`${base.replace(/\/$/,'')}/api/generate`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({model,prompt,system:systemInstruction,stream:false})});if(!r.ok)throw new Error(`OLLAMA_HTTP_${r.status}`);const data=await r.json();return{text:data.response??'',candidates:[{content:{parts:[{text:data.response??''}]}}]} as unknown as GenerateContentResponse;}
export const processUserDirective=async(mode:SystemAspect,contents:Content[],useWebSearch:boolean,deployedCapabilities:DeployedCapability[],isFullCognitionMode:boolean):Promise<GenerateContentResponse>=>{const e=env();const personas=deployedCapabilities.map(c=>functionalCorePrompts[c.id]).filter(Boolean);const systemInstruction=`${baseSystemInstruction}\n${personas.join('\n')}\nModo:${mode}`+(isFullCognitionMode?'\nRaciocínio ampliado solicitado pelo N01; isto não remove salvaguardas do provedor.':'');if((e.N02_AI_PROVIDER||'gemini').toLowerCase()==='ollama')return ollamaGenerate(contents,systemInstruction);const ai=getAiClient();const config:any={temperature:0.6,systemInstruction};if(useWebSearch)config.tools=[{googleSearch:{}}];try{return await ai.models.generateContent({model:'gemini-2.5-flash',contents,config});}catch(error){console.error('Erro Gemini:',error);if(error instanceof Error&&/API_KEY|permission/i.test(error.message))throw new Error('[ERRO DE AUTENTICAÇÃO] Chave Gemini inválida ou sem permissão.');throw new Error('[ERRO DE CONEXÃO] Falha ao processar a solicitação Gemini.');}};
export const transcribeAudio=async(audioBase64:string,mimeType:string):Promise<string>=>{const response=await getAiClient().models.generateContent({model:'gemini-2.5-flash',contents:{parts:[{inlineData:{mimeType,data:audioBase64}},{text:'Transcreva o áudio para português do Brasil. Retorne somente a transcrição.'}]}});return response.text.trim();};
