export type NeuralOperation = "neural.forward@1.0.0" | "neural.learn@1.0.0";
export type NeuralRequest = { operation: NeuralOperation; payload: number[]; correlationId?: string; deadlineMs?: number };
export type NeuralResponse = { traceId: string; correlationId: string; payload?: number[]; data?: unknown; status?: string; error?: string };
const CONTRACT = "1.1.0"; const MESH_VERSION = "1.0";
function randomId(prefix:string){const b=new Uint8Array(16);crypto.getRandomValues(b);return `${prefix}-${Array.from(b,x=>x.toString(16).padStart(2,"0")).join("")}`}
function stable(v:unknown):string{if(v===null||typeof v!=="object")return JSON.stringify(v);if(Array.isArray(v))return `[${v.map(stable).join(",")}]`;const o=v as Record<string,unknown>;return `{${Object.keys(o).sort().map(k=>`${JSON.stringify(k)}:${stable(o[k])}`).join(",")}}`}
async function sign(body:Record<string,unknown>,secret:string){if(secret.length<16)throw new Error("SOUL_MESH_HMAC_SECRET must contain at least 16 characters");const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const u={...body};delete u.hmac;const s=await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(stable(u)));return Array.from(new Uint8Array(s),b=>b.toString(16).padStart(2,"0")).join("")}
export class N07NeuralBridge{private readonly baseUrl:string;private readonly secret:string;private readonly source:"N02";private readonly timeoutMs:number;constructor(source:"N02",options:{baseUrl?:string;secret?:string;timeoutMs?:number}={}){this.baseUrl=(options.baseUrl??process.env.SOUL_N07_URL??"").replace(/\/$/,"");this.secret=options.secret??process.env.SOUL_MESH_HMAC_SECRET??"";this.source=source;this.timeoutMs=options.timeoutMs??15000;if(!this.baseUrl)throw new Error("SOUL_N07_URL is required")}
async invoke(request:NeuralRequest):Promise<NeuralResponse>{if(request.payload.some(v=>!Number.isFinite(v)))throw new Error("neural payload must contain finite numbers");const correlationId=request.correlationId?.trim()||randomId("corr");const envelope:Record<string,unknown>={version:MESH_VERSION,contractVersion:CONTRACT,messageId:randomId("msg"),source:this.source,target:"N07",timestamp:Date.now(),nonce:randomId("nonce"),correlationId,type:"CAPABILITY_REQUEST",payload:{capability:request.operation.split("@")[0],payload:{data:request.payload}}};envelope.hmac=await sign(envelope,this.secret);const c=new AbortController();const t=setTimeout(()=>c.abort(),Math.max(1,request.deadlineMs??this.timeoutMs));try{const r=await fetch(`${this.baseUrl}/api/soul-mesh`,{method:"POST",headers:{"content-type":"application/json","x-soul-contract-version":CONTRACT,"x-soul-correlation-id":correlationId},body:JSON.stringify(envelope),signal:c.signal});const x=await r.json() as Record<string,unknown>;if(!r.ok)throw new Error(String(x.error??`N07 Mesh request failed: ${r.status}`));if(String(x.contractVersion)!==CONTRACT)throw new Error("N07 Mesh response contract mismatch");if(String(x.correlationId)!==correlationId)throw new Error("N07 Mesh correlation mismatch");return{traceId:String(x.id??x.messageId??envelope.messageId),correlationId,payload:Array.isArray(x.payload)?x.payload.map(Number):undefined,data:x.payload,status:String(x.status??"ok")}}finally{clearTimeout(t)}}
forward(payload:number[],correlationId?:string){return this.invoke({operation:"neural.forward@1.0.0",payload,correlationId})}
learn(input:number[],target:number[],correlationId?:string){if(input.length===0||input.length!==target.length)throw new Error("input and target dimensions must match");return this.invoke({operation:"neural.learn@1.0.0",payload:[...input,...target],correlationId})}}
