export type NucleusId='N01'|'N02'|'N03'|'N04'|'N05'|'N06';
export type MeshKind='request'|'response'|'event'|'error';
export type MeshMessage={protocol:'soul-mesh/1';id:string;correlationId:string;source:NucleusId;target:NucleusId;kind:MeshKind;capability?:string;payload:unknown;timestamp:number};
export type PeerDescription={nucleus:NucleusId;peers:NucleusId[];protocol:string;status:string;declaredCapabilities:string[];executableCapabilities:string[];transports:string[];channels?:{in:string[];out:string[]}};
const PEERS:Exclude<NucleusId,'N02'>[]=['N01','N03','N04','N05','N06']; const env=(globalThis as any).process?.env??{};
const urls:Partial<Record<NucleusId,string>>={N01:env.SOUL_MESH_N01_URL,N03:env.SOUL_MESH_N03_URL,N04:env.SOUL_MESH_N04_URL,N05:env.SOUL_MESH_N05_URL,N06:env.SOUL_MESH_N06_URL};
const tokens:Partial<Record<NucleusId,string>>={N01:env.SOUL_MESH_N01_TOKEN,N03:env.SOUL_MESH_N03_TOKEN,N04:env.SOUL_MESH_N04_TOKEN,N05:env.SOUL_MESH_N05_TOKEN,N06:env.SOUL_MESH_N06_TOKEN};
const uuid=()=>globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random()}`;
const valid=(x:unknown):x is MeshMessage=>{if(!x||typeof x!=='object')return false;const m=x as Record<string,unknown>;return m.protocol==='soul-mesh/1'&&typeof m.id==='string'&&typeof m.correlationId==='string'&&typeof m.source==='string'&&typeof m.target==='string'&&typeof m.kind==='string'&&typeof m.timestamp==='number'};
const openDb=()=>new Promise<IDBDatabase>((resolve,reject)=>{if(typeof indexedDB==='undefined')return reject(new Error('INDEXEDDB_UNAVAILABLE'));const r=indexedDB.open('soul-mesh-n02',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('peers'))r.result.createObjectStore('peers',{keyPath:'nucleus'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error??new Error('INDEXEDDB_OPEN_FAILED'))});
export async function listRegisteredPeers(){const d=await openDb();return new Promise<any[]>((resolve,reject)=>{const q=d.transaction('peers','readonly').objectStore('peers').getAll();q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error??new Error('INDEXEDDB_READ_FAILED'))})}
export async function persistPeer(peer:any){const d=await openDb();return new Promise<void>((resolve,reject)=>{const q=d.transaction('peers','readwrite').objectStore('peers').put(peer);q.onsuccess=()=>resolve();q.onerror=()=>reject(q.error??new Error('INDEXEDDB_WRITE_FAILED'))})}
export async function registerWithN01(){const base=urls.N01;if(!base)return false;const manifest=(await import('../../src/soul-mesh/N02MeshManifest')).getN02MeshManifest();const r=await fetch(`${base.replace(/\/$/,'')}/soul-mesh/register`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({nucleus:'N02',endpoint:env.SOUL_MESH_N02_URL,capabilities:manifest.capabilities,protocol:'soul-mesh/1'})});if(!r.ok)return false;const data=await r.json().catch(()=>({}));if(data.token)tokens.N01=data.token;await persistPeer({nucleus:'N01',url:base,token:tokens.N01??null,capabilities:manifest.capabilities,lastSeen:Date.now()});return true;}
async function request(target:NucleusId,capability:string,payload:unknown,timeoutMs=15000,retries=2):Promise<MeshMessage>{const stored=typeof indexedDB!=='undefined'?(await listRegisteredPeers().catch(()=>[])).find((p:any)=>p.nucleus===target):undefined;const url=stored?.url||urls[target];const token=stored?.token||tokens[target];if(!url)throw new Error(`SOUL_MESH_PEER_URL_NOT_CONFIGURED:${target}`);const correlationId=uuid();const message:MeshMessage={protocol:'soul-mesh/1',id:uuid(),correlationId,source:'N02',target,kind:'request',capability,payload,timestamp:Date.now()};let last:unknown;for(let attempt=0;attempt<=Math.min(3,retries);attempt++){const c=new AbortController();const timer=setTimeout(()=>c.abort(),timeoutMs);try{const headers:Record<string,string>={'content-type':'application/json','accept':'application/json'};if(token)headers.authorization=`Bearer ${token}`;const r=await fetch(url,{method:'POST',headers,body:JSON.stringify(message),signal:c.signal});const b:unknown=await r.json().catch(()=>null);if(!valid(b)||b.correlationId!==correlationId||b.source!==target||b.target!=='N02')throw new Error('SOUL_MESH_INVALID_RESPONSE');if(!r.ok||b.kind==='error')throw new Error(`SOUL_MESH_REMOTE_ERROR:${target}`);return b;}catch(e){last=e;if(attempt<Math.min(3,retries))await new Promise(res=>setTimeout(res,250*2**attempt));}finally{clearTimeout(timer)}}throw last instanceof Error?last:new Error(String(last));}
export const sendTo=request; export const requestPeerCapability=request; export const describePeer=async(target:NucleusId,timeoutMs=10000):Promise<PeerDescription>=>{const m=await request(target,'mesh.describe',{from:'N02'},timeoutMs,1);return m.payload as PeerDescription}; export const discoverPeerCapabilities=describePeer; export const requestPeerTool=(target:NucleusId,capability:string,payload:unknown,timeoutMs=15000)=>request(target,capability,payload,timeoutMs,1); export const pingAll=(timeoutMs=5000)=>Promise.all(PEERS.map(async target=>{try{return{target,status:'CONNECTED' as const,response:await request(target,'mesh.health',{from:'N02'},timeoutMs,1)}}catch(error){return{target,status:'FAILED' as const,error:String(error)}}})); export const N02_OUT_CHANNELS=PEERS.map(x=>`N02.OUT.${x}`); export const N02_IN_CHANNELS=PEERS.map(x=>`N02.IN.${x}`);
