import { createHmac, randomInt } from 'node:crypto';
export type NucleusId='N01'|'N02'|'N03'|'N04'|'N05'|'N06'|'N07';
export type MeshKind='request'|'response'|'event'|'error';
export type SoulMeshMessage={protocol:'soul-mesh/1';contractVersion:'1.1.0';id:string;correlationId:string;source:NucleusId;target:NucleusId;kind:MeshKind;capability:string;payload:unknown;timestamp:number;meta?:{runtime?:string;transport?:string;encoding?:string;version?:string;nonce?:string;traceId?:string}};
export type PeerDescription={nucleus:NucleusId;peers:NucleusId[];protocol:string;status:string;declaredCapabilities:string[];executableCapabilities:string[];transports:string[];channels?:{in:string[];out:string[]}};
export type PeerFailureSnapshot={attempts:number;retryableFailures:number;circuitOpens:number;fallbacks:number;failuresByPeer:Record<string,number>};
const PEERS:Exclude<NucleusId,'N02'>[]=['N01','N03','N04','N05','N06','N07'];
const env=(globalThis as any).process?.env ?? {};
const urls:Partial<Record<NucleusId,string>>={N01:env.SOUL_MESH_N01_URL,N03:env.SOUL_MESH_N03_URL,N04:env.SOUL_MESH_N04_URL,N05:env.SOUL_MESH_N05_URL,N06:env.SOUL_MESH_N06_URL,N07:env.SOUL_MESH_N07_URL};
const tokens:Partial<Record<NucleusId,string>>={N01:env.SOUL_MESH_N01_TOKEN,N03:env.SOUL_MESH_N03_TOKEN,N04:env.SOUL_MESH_N04_TOKEN,N05:env.SOUL_MESH_N05_TOKEN,N06:env.SOUL_MESH_N06_TOKEN,N07:env.SOUL_MESH_N07_TOKEN};
const secret=env.SOUL_MESH_HMAC_SECRET?.trim() ?? '';
const uuid=()=>globalThis.crypto?.randomUUID?.() ?? `n02-${Date.now()}-${randomInt(1_000_000)}`;
const traceId=()=>uuid().replaceAll('-','').slice(0,32).padEnd(32,'0');
const spanId=()=>uuid().replaceAll('-','').slice(0,16).padEnd(16,'0');
const metrics={attempts:0,retryableFailures:0,circuitOpens:0,fallbacks:0,failuresByPeer:new Map<string,number>()};
const circuit=new Map<NucleusId,{failures:number;openUntil:number}>();
const BREAKER_THRESHOLD=3;
const BREAKER_COOLDOWN_MS=10_000;
const valid=(x:unknown):x is SoulMeshMessage=>{if(!x||typeof x!=='object')return false;const m=x as Record<string,unknown>;return m.protocol==='soul-mesh/1'&&m.contractVersion==='1.1.0'&&typeof m.id==='string'&&m.id.length>0&&m.id.length<=200&&typeof m.correlationId==='string'&&m.correlationId.length>0&&m.correlationId.length<=200&&typeof m.source==='string'&&/^N0[1-7]$/.test(m.source)&&typeof m.target==='string'&&/^N0[1-7]$/.test(m.target)&&typeof m.kind==='string'&&['request','response','event','error'].includes(m.kind as string)&&typeof m.capability==='string'&&m.capability.length>0&&m.capability.length<=200&&typeof m.timestamp==='number'&&Number.isFinite(m.timestamp)};
function peerUrl(target:NucleusId){const url=urls[target];if(!url)throw new Error(`SOUL_MESH_PEER_URL_NOT_CONFIGURED:${target}`);return url}
function canonical(m:SoulMeshMessage,n:string){return JSON.stringify({protocol:m.protocol,contractVersion:m.contractVersion,id:m.id,correlationId:m.correlationId,source:m.source,target:m.target,kind:m.kind,capability:m.capability??null,payload:m.payload,timestamp:m.timestamp,meta:m.meta??null,nonce:n});}
function sign(m:SoulMeshMessage,n:string){return createHmac('sha256',secret).update(canonical(m,n),'utf8').digest('hex');}
function retryable(error:unknown):boolean{if(!(error instanceof Error))return false;return /SOUL_MESH_(TIMEOUT|INVALID_RESPONSE|REMOTE_ERROR)|fetch failed|network|econn|socket|temporar|unavailable|overload/i.test(error.message)}
function noteFailure(target:NucleusId){metrics.failuresByPeer.set(target,(metrics.failuresByPeer.get(target)??0)+1)}
function breakerOpen(target:NucleusId):boolean{const state=circuit.get(target);if(!state)return false;if(Date.now()>=state.openUntil){circuit.delete(target);return false}return true}
function noteSuccess(target:NucleusId){circuit.delete(target)}
function noteRetryableFailure(target:NucleusId){const state=circuit.get(target)??{failures:0,openUntil:0};state.failures+=1;noteFailure(target);if(state.failures>=BREAKER_THRESHOLD){state.openUntil=Date.now()+BREAKER_COOLDOWN_MS;metrics.circuitOpens+=1}circuit.set(target,state)}
export function peerFailureSnapshot():PeerFailureSnapshot{return{...metrics,failuresByPeer:Object.fromEntries(metrics.failuresByPeer)}}
export function resetPeerFailureMetrics():void{metrics.attempts=0;metrics.retryableFailures=0;metrics.circuitOpens=0;metrics.fallbacks=0;metrics.failuresByPeer.clear();circuit.clear()}

async function request(target:NucleusId,capability:string,payload:unknown,timeoutMs=15000,retries=1):Promise<SoulMeshMessage>{const url=peerUrl(target);if(breakerOpen(target))throw new Error(`SOUL_MESH_CIRCUIT_OPEN:${target}`);const correlationId=uuid();const nonceValue=uuid().replaceAll('-','').padEnd(32,'0').slice(0,32);const message:SoulMeshMessage={protocol:'soul-mesh/1',contractVersion:'1.1.0',id:uuid(),correlationId,source:'N02',target,kind:'request',capability,payload,timestamp:Date.now(),meta:{runtime:'Eternium-',transport:'HTTP',encoding:'json',version:'1.1.0',nonce:nonceValue,traceId:correlationId}};let last:unknown;const maxAttempts=Math.min(3,Math.max(0,retries))+1;for(let attempt=0;attempt<maxAttempts;attempt++){metrics.attempts+=1;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),Math.max(250,timeoutMs));try{const headers:Record<string,string>={'content-type':'application/json','accept':'application/json','traceparent':`00-${traceId()}-${spanId()}-01`,'x-soul-correlation-id':correlationId};if(secret)headers['x-soul-mesh-hmac']=sign(message,nonceValue);else if(tokens[target]){headers.authorization=`Bearer ${tokens[target]}`;metrics.fallbacks+=1}else if(env.NODE_ENV==='production')throw new Error('SOUL_MESH_AUTH_NOT_CONFIGURED');const response=await fetch(url,{method:'POST',headers,body:JSON.stringify(message),signal:controller.signal});const body:unknown=await response.json().catch(()=>null);if(!valid(body)||body.correlationId!==correlationId||body.source!==target||body.target!=='N02')throw new Error('SOUL_MESH_INVALID_RESPONSE');if(!response.ok||body.kind==='error')throw new Error(`SOUL_MESH_REMOTE_ERROR:${target}:${body.capability}`);noteSuccess(target);return body;}catch(error){last=error;if(!retryable(error)||attempt>=maxAttempts-1){noteFailure(target);break}metrics.retryableFailures+=1;noteRetryableFailure(target);if(breakerOpen(target))break;const base=Math.min(2000,250*2**attempt);const jitter=randomInt(Math.max(1,Math.floor(base*0.2)+1));await new Promise(resolve=>setTimeout(resolve,base+jitter))}finally{clearTimeout(timer)}}throw last instanceof Error?last:new Error(String(last));}
export const sendTo=request;export const requestPeerCapability=request;
export const describePeer=async(target:NucleusId,timeoutMs=10000):Promise<PeerDescription>=>{const message=await request(target,'mesh.describe',{from:'N02',intent:'capability-discovery'},timeoutMs,1);return message.payload as PeerDescription};
export async function discoverPeerCapabilities(target:NucleusId,timeoutMs=10000){return describePeer(target,timeoutMs)}
export async function requestPeerTool(target:NucleusId,toolCapability:string,payload:unknown,timeoutMs=15000){return request(target,toolCapability,payload,timeoutMs,1)}
export async function pingAll(timeoutMs=5000){return Promise.all(PEERS.map(async target=>{try{return{target,status:'CONNECTED' as const,response:await request(target,'mesh.ping',{from:'N02',channel:`N02.OUT.${target}`},timeoutMs,1)}}catch(error){return{target,status:'FAILED' as const,error:String(error)}}}))}
export const N02_OUT_CHANNELS=PEERS.map(x=>`N02.OUT.${x}`);export const N02_IN_CHANNELS=PEERS.map(x=>`N02.IN.${x}`);
